name: CI

on:
  - push

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install --recursive --frozen-lockfile --strict-peer-dependencies
      - run: pnpm run lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install --recursive --frozen-lockfile --strict-peer-dependencies
      - run: pnpm run test:coverage
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

  building:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install --recursive --frozen-lockfile --strict-peer-dependencies
      - run: pnpm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
